image: alpine:3.20.0

stages:
  - build
  - deploy

## all branchs can build html
build:
  image: node:22.11.0-alpine3.20
  tags: [pages]
  stage: build
  before_script:
    - yarn install --registry https://registry.npm.taobao.org 
  script:
    - yarn build
  cache:
    key: docusaurus-3.6.3 # caching by docusaurus version.
    paths:
    - node_modules/
  artifacts:
    paths:
    - build

pages:
  tags: [pages]
  stage: deploy
  script:
  - mv build public
  artifacts:
    paths:
    - public
  only:
  - master
