image: alpine:3.12.0

stages:
  - build
  - deploy

## all branchs can build html
build:
  image: node:16.16.0-alpine
  tags: [pages]
  stage: build
  before_script:
    - yarn install --registry https://registry.npm.taobao.org 
  script:
    - yarn build
  cache:
    key: docusaurus-2.0.0-rc1 # caching by docusaurus version.
    paths:
    - node_modules/
  artifacts:
    paths:
    - build

pages:
  tags: [pages]
  stage: deploy
  script:
  - mv build public
  artifacts:
    paths:
    - public
  only:
  - master
