# this is an example of gitlab-page rep.
image: debian:7.11-slim 
# test for using image not in runner

pages:
  tags:
  - pages
  stage: deploy
  script:
  - echo 'Nothing to do...'
  artifacts:
    paths:
    - public
  only:
  - master
